# Generated by Django 3.1.11 on 2021-05-16 18:09

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0003_testuseruuidmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='querysetrule',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='body_html_template',
            field=models.TextField(blank=True, default='<br /><br /><p style="text-align:center;font-size:small;">Click <a href="https://{{ unsubscribe }}">here</a> to unsubscribe from future emails.</p>', help_text='You will have settings and user in the context. For example {{ user.first_name }} {{ user.last_name }}will return "Joe Smith", and {{ settings.BASE_URL }} will return your domain name.', null=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='from_email',
            field=models.EmailField(blank=True, default=settings.DEFAULT_FROM_EMAIL, help_text='Set a custom from email.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='drip',
            name='from_email_name',
            field=models.CharField(blank=True, default=settings.EMAIL_ADMIN, help_text='Set a name for a custom from email.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='querysetrule',
            name='drip',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='queryset_rules', to='drip.drip'),
        ),
        migrations.AlterField(
            model_name='querysetrule',
            name='field_name',
            field=models.CharField(choices=[('id', 'User id'), ('is_superuser', 'Is admin?'), ('is_staff', 'Is staff member?'), ('first_name', 'First name'), ('last_name', 'Last name'), ('email', 'Email address'), ('is_active', 'Is signup activated?'), ('socialaccount__is_active', 'Is signup activated? (social signups only)'), ('is_subscribed', 'Is email subscribed?'), ('socialaccount__is_subscribed', 'Is email subscribed? (social signups only)'), ('date_joined', 'Date joined'), ('socialaccount__date_joined', 'Date joined (social signups only)'), ('last_login', 'Last login'), ('socialaccount__last_login', 'Last login (social signups only)'), ('groups', 'Member of group'), ('socialaccount__groups', 'Member of group (social signups only)')], default='last_login', max_length=100),
        ),
        migrations.AlterField(
            model_name='querysetrule',
            name='lookup_type',
            field=models.CharField(choices=[('exact', 'exactly'), ('iexact', 'exactly (case insensitive)'), ('contains', 'contains'), ('icontains', 'contains (case insensitive)'), ('regex', 'regex'), ('iregex', 'regex (case insensitive)'), ('gt', 'greater than'), ('gte', 'greater than or equal to'), ('lt', 'less than'), ('lte', 'less than or equal to'), ('startswith', 'starts with'), ('istartswith', 'starts with (case insensitive)'), ('endswith', 'ends with'), ('iendswith', 'ends with (case insensitive)')], default='exact', max_length=100),
        ),
        migrations.AlterField(
            model_name='querysetrule',
            name='method_type',
            field=models.CharField(choices=[('filter', 'Filter'), ('exclude', 'Exclude')], default='filter', max_length=100),
        ),
    ]
