# Generated by Django 3.1.11 on 2021-05-20 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0004_auto_20210516_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentdrip',
            name='name',
            field=models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.CASCADE, to='drip.drip', to_field='name'),
        ),
    ]
