# Generated by Django 3.1.11 on 2021-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0005_sentdrip_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='body_html_template',
            field=models.TextField(blank=True, default='<br /><br /><p style="text-align:center;font-size:small;">Click <a href="https://{{ unsubscribe }}">here</a> to unsubscribe from future emails.</p>', help_text='You have all of the user fields in the context. For example {{ first_name }} {{ last_name }} will return "Joe Smith".', null=True),
        ),
    ]
