# Generated by Django 3.1.11 on 2021-06-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0006_auto_20210605_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querysetrule',
            name='field_name',
            field=models.CharField(choices=[('id', 'User id'), ('is_superuser', 'Is admin?'), ('is_staff', 'Is staff member?'), ('first_name', 'First name'), ('last_name', 'Last name'), ('email', 'Email address'), ('is_active', 'Is signup activated?'), ('socialaccount__is_active', 'Is signup activated? (social signups only)'), ('is_mailsubscribed', 'Is email subscribed?'), ('socialaccount__is_mailsubscribed', 'Is email subscribed? (social signups only)'), ('date_joined', 'Date joined'), ('socialaccount__date_joined', 'Date joined (social signups only)'), ('last_login', 'Last login'), ('socialaccount__last_login', 'Last login (social signups only)'), ('groups', 'Member of group'), ('socialaccount__groups', 'Member of group (social signups only)')], default='last_login', max_length=100),
        ),
    ]
