# Generated by Django 3.2.5 on 2021-07-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drip', '0008_auto_20210611_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drip',
            name='from_email',
            field=models.EmailField(blank=True, default='admin@robertnclayton.net', help_text='Set a custom from email.', max_length=254, null=True),
        ),
    ]
